BaseAdresseNationale/ban-plateforme

- lib/compose/extract-lieux-dits.js
- lib/compose/index.js
- lib/compose/products/adresses-lo.js
- lib/compose/products/adresses-odbl.js
- lib/distribute/index.js
- lib/distribute/writers/addok.js
- lib/distribute/writers/csv.js
- lib/merge/index.js
Les numéros virtuels (supérieurs à 5000) ne sortent pas dans les fichiers consolidés.
Cela a pour conséquence la perte des voies qui ne contiennent que des numéros virtuels.
Si évidemment dans de nombreux cas, ces voies n'ont pas d'intérêt, pour les villages mal ou peu adressés, ce sont les seuls informations disponibles.
Cette PR produit une voie de type "locality" dès lors que toutes les adresses de cette voie sont virtuelles.
Cette PR n'a d'impact que sur les fichiers addok.
Les toponymes issus des BAL seront ajoutés dans une PR ultérieure.
> Ajouts de certains lieux-dits du cadastre

- lib/import/sources/ign-api-gestion.js
Le type de position d'une adresse issue de la source API de gestion (`type_loc`) était importé de façon incorrecte.
C'est désormais corrigé, et le type est désormais converti en type "BAL".
L'attribut `lieuDitComplementNom` est quand à lui désormais importé à partir du champ `nom_complementaire` du format d'export API de gestion.
> Import du type de position et du nom de lieu dit (API de gestion)

- package.json
- yarn.lock
Mise à jour de toutes les dépendances, à l'exception de :
```
bull        3.29.3  3.29.3 4.8.3  dependencies https://github.com/OptimalBits/bull#readme
got         11.8.3  11.8.3 12.0.4 dependencies https://github.com/sindresorhus/got#readme
into-stream 6.0.0   6.0.0  7.0.0  dependencies https://github.com/sindresorhus/into-stream#readme
leven       3.1.0   3.1.0  4.0.0  dependencies https://github.com/sindresorhus/leven#readme
lru-cache   6.0.0   6.0.0  7.10.1 dependencies https://github.com/isaacs/node-lru-cache#readme
ora         5.4.1   5.4.1  6.1.0  dependencies https://github.com/sindresorhus/ora#readme
rev-hash    3.0.0   3.0.0  4.0.0  dependencies https://github.com/sindresorhus/rev-hash#readme
```
`got` `into-stream` `leven` `ora` et `rev-hash` sont désormais ES Modules …
> Mise à jour des dépendances

- lib/compose/strategies/bal/numero.js
Jusqu'à aujourd'hui la position était sélectionnée de façon relativement aléatoire (la première de la liste, sans que l'ordre de la liste ne soit stable).
Désormais le choix est fait parmi les positions, en sélectionnant la position de type le plus fort.
Si plusieurs positions ont le même type, l'algorithme reste non stable.
La première proposition de priorisation est la suivante :
```js
const POSITION_TYPES_PRIORITY = {
entrée: 10,
bâtiment: 8,
'cage d’escalier': 7,
logement: 6,
'service technique': 5,
segment: 4,
'délivrance postale': 3,
parcelle: 1
}
```
> Ajout d'un algorithme stabilisant le choix de la position de référence

- server.js
Cette PR corrige la prise en compte du fichier `.env` qui a été supprimée.
> Ajoute la prise en compte du `.env` pour `server.js`

- .env.sample
- lib/import/sources/bal.js
Il y avait une erreur de syntaxe.
J'ai convergé vers `{dep}` qui est du coup cohérent avec le RIL.
> Correction BAL_URL_PATTERN

- lib/api/routes.js
- lib/formatters/csv-bal.js
Modification pour l'export bal csv, option sur prepareData pour les LR.
Par défaut on n'inclut pas les LR pour prendre en compte le fait qu'on exporte pas les LR sur les exports départementaux.
> Modification pour l'export BAL CSV départemental vs communal

- .github/workflows/node.js.yml
- lib/compose/processors/recompute-codes-voies.js
- lib/compose/strategies/bal/lieux-dits.js
- lib/compose/strategies/bal/numero.js
- lib/compose/strategies/bal/voies.js
- lib/compose/strategies/multi-sources/voies.js
- lib/distribute/writers/addok.js
- lib/formatters/csv-bal.js
- lib/formatters/csv-legacy.js
- lib/util/__tests__/string.js
- lib/util/string.js
- package.json
Cette PR veille à convertir les libellés en majuscules (et uniquement ceux-là) au moment de la production de la BAN (étape `compose`).
L'opération utilise la fonction `beautify` du dépôt https://github.com/BaseAdresseNationale/adresses-util.
Les champs ciblés sont : `nomVoie` et `lieuDitComplementNom` ainsi que leurs variantes en langues régionales.
J'ai profité de cette PR pour activer les tests unitaires qui étaient présents, et créé des tests unitaires pour cette nouvelle fonctionnalité.
GitHub Actions est aussi paramètre dans cette PR.
> Amélioration des libellés en majuscule

- .env.sample
- lib/api/routes.js
- lib/compose/import-from-api-depot.js
- lib/compose/index.js
- lib/compose/sources/bal.js
- lib/compose/strategies/bal/numero.js
- lib/formatters/csv-bal.js
- lib/formatters/geojson.js
- lib/models/commune.js
- lib/util/api-depot.js
- package.json
- yarn.lock
Lorsqu'une BAL est présente sur l'API de dépôt, la composition du référentiel BAN pour cette commune utilise direction l'API de dépôt, et ne passe plus par l'étape d'import du fichier intermédiaire `adresses-locales` ana `import/bal`.
Tous les champs du format BAL sont mappés sur le modèle d'entrée (`sources_adresses`) sans transiter par la collection MongoDB.
TODO:
> Composition à partir de l'API de dépôt

- lib/compose/index.js
- lib/models/commune.js
- scripts/update-cog.js
Le fonctionnement initial effectuait une étape `compose` à chaque appel, y compris si la révision source était inchangée.
Avec cette adaptation l'étape `compose` est annulée si la révision courante est identique à celle enregistrée dans la base de données.
Il est possible de déroger à ce comportement en passant `{force: true}`, ce qui va être pertinent notamment quand on modifie un algorithme de transformation des adresses.
> Ne déclencher la "composition" que si les adresses ont changé sur l'API de dépôt

- .env.sample
- lib/api/routes.js
Cette PR a pour objectif de mettre à disposition une route protégée permettant de demander manuellement l'opération `compose` pour une commune donnée.
- Nouvelle variable d'environnement `ADMIN_TOKEN`
- Ajout d'un middleware `ensureIsAdmin` protégeant les appels administrateur
- Nouvelle route `POST /ban/communes/:codeCommune/compose` déclenchant l'opération `compose` pour la commune précisée en paramètre. Cette route renverra la commune mise à jour.
> Route permettant de déclencher la consolidation des adresses d'une commune

- lib/api/routes.js
try catch sur route compose pour la promesse dans route.js
Ecriture dans un fichier errorCompose.log à la racine de ban-plateforme.
exemple : 
--- 
Fri, 18 Nov 2022 13:17:24 GMT
codeCommune : 59656 
erreur : Error: et bim
---
Permet de savoir quelles communes ont planté et de les relancer à la main.
En attendant une solution pérenne.
> fix partiel erreur compose

- lib/compose/sources/cadastre.js
Une mise à jour de la constante ACCEPT_DESTINATIONS a été effectué en se basant sur les [adresses-cadastres](https://github.com/BaseAdresseNationale/adresses-cadastre/commit/172b8071f487de7f39d605b0ad18b4112c3aba77).
Fix #46
> Mise à jour Accept_destinations pour fichier cadastre.js

- lib/compose/processors/filter-out-of-commune.js
- lib/compose/sources/ftth.js
Compte-tenu de la non-qualité du fichier du déploiement FTTH de l'Arcep, il arrive fréquemment que des adresses ne soient pas attribuées à la bonne commune.
S'il est légitime d'accepter des adresses qui débordent légèrement du contour de la commune en raison des contraintes de voirie et d'adressage, il est clair que sur cette source de données la limite à 5km est excessive et génère beaucoup d'erreurs.
Cette pull request introduit un paramètre `maxDistance` pour le traitement de filtrage des adresses hors de la commune.
Il est défini par défaut à `5` par cohérence avec le comportement actuel.
La paramètre est ensuite fixé à `0.2` soit 200 mètres pour la source FTTH.
> Réduction du périmètre de prise en compte des adresses FTTH

- .env.sample
This pull request aims to clean the .env.sample file so that we always have a file up-to-date with the used variables
The following env variables are used nowhere in the ban-plateforme code : 
- MAJIC_PATH
- BAL_URL_PATTERN
> Deleted useless env variables in sample file

- lib/models/commune.js
Test lorsqu'on trouve un document dans le lookup des voies si c'est un lieu dit on ajoute les numéros liés (ie ceux qui ont llieux dit complement Nom rempli avec le libellé du lieux dit sur la commune).
Cela donne pour la Haute Folie à Breux sur Avre : (extrait)
**On récupère dans le numéro l'idVoie qui permettra ensuite de classer les numéros en les groupant par voie.
Il faudra donc faire une requête supplémentaire par idVoie pour récupérer le libellé à afficher dans la liste de l'explorateur adresse.data.gouv.fr.**
{
"id": "27115_B023",
"type": "lieu-dit",
"idVoie": "27115_B023",
"nomVoie": "La Haute Folie",
"nomVoieAlt": {},
"dateMAJ": "2020-07-03",
"displayBBox": [
1.0797,
48.7713,
1.0824,
48.7731
],
"commune": {
"id": "27115",
"nom": "Breux-sur-Avre",
"code": "27115",
"departement": …
> modification route lookup pour les lieux-dit ajout des numéros liés

- lib/api/address/__mocks__/data-mock.js
- lib/api/address/consumers.js
- lib/api/address/models.js
- lib/api/address/routes.js
- lib/api/address/utils.js
- lib/api/address/utils.spec.js
Cette PR va ajouter 1 nouvelle route, pour la mise à jour d'adresses, à l'API de BAN-Platform :
_**A noter** : Actuellement, les traitements de données se font sur une collection indépendante, nommée address_test_
Les tests peuvent être lancés via la commande :
```sh
yarn test
```
**A noter :**
_Cette route nécessite un token de connexion de 36 caractères, qui doit, au préalable, être renseignés sur la variable d'environnement `BAN_API_AUTHORIZED_TOKENS` et passé en 'en-tête' lors de l'appel à la route (`Authorization: token MON_TOKEN_DE_36_CARACTERES_xxxxxxxxx`)._ 
_Un token peut être généré localement en passant la commande `npx nanoid --alphabet 123456789ABCDEFGHJKMNPQRSTVWXYZ --size 36` dans un terminal (cette commande nécessite la présence de `npm`)_
Mise à jour d'adresses. …
> BanID : Ajout d'une route d'api PUT pour la modification d'adresses

- lib/api/address/models.js
- lib/api/address/routes.js
This pull request aims to add a new route to be able to delete an address with its ID.
Request : DELETE API_BASE_URL/address/{addressID}
The api will check if the ID is existing. If existing, it will try to delete it. If not, it will throw a 404 error ('Request ID unknown')
> Added new api DELETE route for unitary address

- package.json
- yarn.lock
Context : Windows command prompt is crashing when meeting environment variables set this way : NODE_OPTIONS=--experimental-vm-modules.
Action : In order to solve the issue, the "cross-env" package has been installed and added to the "test" script : 
`"test": "cross-env NODE_OPTIONS=--experimental-vm-modules jest"`
> Fix test script for cross env

- lib/api/address/__mocks__/address-data-mock.js
- lib/api/address/schema.js
- lib/api/address/utils.spec.js
Context : In order to complete the address schema on new banID api, we need to add the following fields : 
```
idVoie : string,
parcelles : string [],
certifie : boolean,
positions : Position [],
```
Specific types : 
```
Position : 
geometry : {
type: 'Point'
coordinates: Coordinates
},
type: PositionType
```
```
Coordinates : [number, number]
```
```
PoisitionType : "entrée"|"bâtiment"|"cage d'escalier"|"logement"|"service technique"|"délivrance postale"|"parcelle"|"segment"|"autre"
```
> Modified address schema for BanID api

- lib/compose/processors/recompute-codes-voies.cjs
pour le problème d'orthez.
on passe par composeCommune (ban-plateforme\lib\compose\index.cjs)
puis dans const balData = isBAL && await getBalData(codeCommune, currentRevision)
la function getBalData appelle prepareData qui appelle recomputeCodesVoies
-> cette function permet de retrouver le code de voie (idVoie) 
-> or il n'était pas reporté sur les adresses. **(cf ajout de code de la PR)**
Mais de retour dans index.cjs on passe dans buildVoies (ban-plateforme\lib\compose\strategies\bal\voies.cjs) qui appelle computeGroups et se sert de l'idVoie. (il n'était pas remplit dans les adresses alors qu'on en avait trouvé un).
-> résultat dans la BAN actuelle  db.voies.find({codeCommune : '64430', nomVoie: 'Rue De Labestaa'}).pretty() -> 2 voies.
-> en local si on lance le compose de la commune …
> correction code idVoie trouvé non exploité

- docker-compose.yml
- process.dev.yml
I. Context : 
When ban-plateforme is running (worker and server) and code is modified during local development, the docker container has to be restarted to take the changes into account.
II. Enhancement : 
This pull request adds the watch behavior on code that is part of the following folder and file list : 
- lib (folder)
- scripts (folder)
- server.js (file)
- worker.js (file)
III. How to test : 
- Launch the docker containers by starting the following command : 
`docker-compose up --build -d`
- Modify the code and see if the worker or/and the server is restarted in the 'api' terminal container
> Added watch behavior for docker implementation

- lib/api/address/utils.js
- lib/api/common-toponym/__mocks__/common-toponym-models.js
- lib/api/common-toponym/models.js
- lib/api/common-toponym/routes.js
- lib/api/common-toponym/utils.js
Context : 
When a BAL is going to be published with BAN-IDs, we need to be able to get the information of which common toponym have to be created, which have to be updated and which have to be deleted. 
Enhancements : 
We have created a new api route that returns a delta report. Here are the information about this route : 
- endpoint : /common-toponym/delta-report
- body : `{commonToponymIDs:[...], codeCommune:'...'}` (commonToponymIDs array and codeCommune string are mandatory)
- response : `{idsToCreate:[...], idsToUpdate:[...], idsToDelete:[...], idsUnauthorized}`
How to test : 
In your local environnement, insert two news addresses with the POST /common-toponym route. Here is an example of the body : 
```
[
{
"id": "00000000-0000-4fff-9fff-00000000002a",
"codeCommune": "12345", …
```
> Added common toponym ID delta report api route + fix

- lib/compose/bal-garbage-collector/__mocks__/api-depot-mock.js
- lib/compose/bal-garbage-collector/__mocks__/compose-mock.js
- lib/compose/bal-garbage-collector/__mocks__/models-mock.js
- lib/compose/bal-garbage-collector/__mocks__/revision-data-mock.js
- lib/compose/bal-garbage-collector/index.js
- lib/compose/bal-garbage-collector/index.spec.js
- lib/compose/bal-garbage-collector/models.js
- lib/util/api-depot.cjs
- worker.js
#129
Actuellement, lors de déploiement pour mise en production de nouveau code, l'API BAN peut ne pas répondre pendant quelques minutes. L'API de dépôt appelle l'API BAN lors de la mise à jour d'une BAL. En cas d'indisponibilité de l'API BAN elle ne traite pas l'erreur et ne re-tente pas la publication.
Cette PR permet lors du lancement de l'API BAN de comparer l'id de révision des BAL de l'API dépôt avec l'id de révision qui est dans la BAN et de lancer une récupération de la BAL si les id de révision ne correspondent pas.
> création commande de composition "ramasse miette"

- lib/models/commune.cjs
- worker.js
This PR is to solved the issue raised by @IGNFBourcier in this other PR : https://github.com/BaseAdresseNationale/ban-plateforme/pull/159
Context : 
We have added a job id to the job that is sent to the queue each time a composition is asked (function askComposition() from the file lib/models/comune.cjs). The job id has been added so that there is only one job with this ID in the queue.
The issue is that, before the job is sent, the data base is updated with : 
```
await mongo.db.collection('communes').findOneAndUpdate(
{codeCommune: communeActuelle.code},
{$set: {compositionAskedAt: now, compositionOptions: options}},
{upsert: true} 
)
```
And when the job is taken by a consumer, the first thing that is done is to check if the date in the data base and in the job data is the same : 
``` …
```
> fix job ids

- lib/api/common-toponym/utils.spec.js
- lib/api/consumers/api-consumer.js
- lib/api/district/__mocks__/district-data-mock.js
- lib/api/district/__mocks__/district-models.js
- lib/api/district/models.js
- lib/api/district/routes.js
- lib/api/district/schema.js
- lib/api/district/utils.js
- lib/api/district/utils.spec.js
- server.js
Context : 
To be able to manipulate district data in the ban data base, we need to add api routes to get, create, modify and delete districts.
Enhacements : 
New api routes : 
- GET /district/{districtID}
- POST /district & PUT /district
body exemple : 
```
[
{
"id": "00000000-0000-4fff-9fff-00000000000a",
"label": [
{
"isoCode": "fr",
"value": "commune A"
}
]
}
]
```
- DELETE /district/{districtID}
- POST /district/delete
body exemple : 
`["00000000-0000-4fff-9fff-00000000000a","00000000-0000-4fff-9fff-00000000000b"]`
> District API routes (GET, POST, PUT, DELETE)

- lib/compose/processors/recompute-codes-voies.cjs
- lib/compose/sources/bal.cjs
Permet de corriger sur les BAL des fusions non désirées.
Exemple de correction.
Les numéros 20, 24 et 80 auparavant attribués à la Route de la Chaze injustement sont maintenant bien sur la Rue des 2 Fontaines.
uid_adresse | cle_interop | commune_insee | commune_nom | commune_deleguee_insee | commune_deleguee_nom | voie_nom | lieudit_complement_nom | numero | suffixe | position | x | y | long | lat | cad_parcelles | source | date_der_maj | certification_commune
  | 48009_is5ni3_00020 | 48009 | Peyre en Aubrac | 48060 | Fau-de-Peyre | Rue des 2 Fontaines | SalÃ¨les | 20 |   | entrÃ©e | 716734.67 | 6406107.3 | 3.211442 | 44.7539 | 480090600A0203 | commune | 01/03/2023 | 1 |  
  | 48009_is5ni3_00024 | 48009 | Peyre en Aubrac | 48060 | Fau-de-Peyre | Rue des 2 Fontaines | SalÃ¨les | 24 |   | …
> ajout option qui interdit la réattribution d'un idFantoir BAL

- lib/compose/compose-all-force.cjs
- package.json
Cette PR permet de composer en mettant force true à toutes les communes.
A utiliser avec parcimonie.
Elle permet de remettre à jour les communes ayant une BAL à jour en cas de correction sur le calcul du fantoir dans la BAN par exemple.
> ajout d'un script permettant de tout composer

- nodemon.json
- process.dev.yml
Context : currently, the "watch" mechanism of pm2 (for Docker local deployment) and the nodemon mechanism (for local deployment not using Docker) is restarting the ban-api and/or the ban-worker when files are appearing/changing in the "dist" & "data" folder, which is not a desired behavior. 
Enhancement : a "ignore" pattern as been added : 
- to the watch mechanism in the process.dev.yml file (setting file for pm2).
- to the nodemon mechanism by adding a nodemon.json file
> Added "ignore" patterns for nodemon/watch mechanism to improve local deployment (with and without Docker)

- lib/api/address/__mocks__/address-data-mock.js
- lib/api/address/schema.js
- lib/api/address/utils.js
- lib/api/ban-id/models.js
- lib/api/common-toponym/__mocks__/common-toponym-data-mock.js
- lib/api/common-toponym/models.js
- lib/api/common-toponym/schema.js
- lib/api/common-toponym/utils.js
- lib/api/district/__mocks__/district-data-mock.js
- lib/api/district/schema.js
- lib/api/district/utils.js
- lib/api/schema.js
I. Context : 
As our specification begins to get clearer, we need to modify the current BAN-ID data schema. 
==> **[Here is the up-to-date specification for BAN-ID data schema](https://github.com/BaseAdresseNationale/ban-plateforme/wiki/DRAFT%23-Schema-de-la-base-de-donn%C3%A9es-BAN)** <==
In the current schema, this PR is : 
- adding the "mainCommonToponymID" and "secondaryCommonToponymIDs" fields on address schema,
- adding the "meta" field in Address/CommonToponym/District (in which we will add the data relative to other organisms as Insee, cadastre, ...),
- modifying the position type list to fit INSPIRE equivalent,
- adding "updateDate" on CommonToponym and District (as a required field).
This PR also unify the UUID for all IDs (address, commonToponym, district)
> Modified BAN-ID data schema

- lib/api/district/models.js
- lib/api/district/routes.js
I. Context : 
In order for data producers to be able to get districts (and especially districtIDs) from the cog ("code officiel géographique" or also "code commune"), we need to expose a new api route.
This PR aims to add this following api route : 
`GET district/cog/:cog` ==> No tokens required.
Example of request : 
`GET district/cog/12345`
Example of response with code 200 : 
```
[
{
"id": "00000000-0000-4fff-9fff-00000000000a",
"label": [
{
"isoCode": "fra",
"value": "commune de 12345"
}
],
"updateDate": "2023-06-23",
"meta": {
"insee": {
"cog": "12345"
}
}
}
]
```
> Added route to get dristricts from cog

- .env.sample
- .gitignore
- docker-compose.yml
- nodemon.json
- package.json
- process.dev.yml
- start.dev.sh
- toolbox.dev/scripts/compare-data-from-db-snapshot-and-current-db.js
- toolbox.dev/scripts/db-snapshot.js
- yarn.lock
I. Context : 
When making code changes locally, it is sometimes difficult to have a clear view of what is the repercussion on data processing.
This PR aims to add a dev toolbox at the root of the project to help the developper when coding locally. 
This toolbox is initiated with 2 scripts : 
1- `db-snapshot.js` to make a DB snapshot (DB cloned in files) => This script creates a folder where it stores all the collections in json files.
2- `compare-data-from-db-snapshot-and-current-db` to compare the data from the snapshot and from the current DB running locally => This script reads the files from the snapshot, read the data in the current DB and builds a report to inform the developper what has been added, deleted and modified.
Example of use : 
"I would like to …
> Add toolbox script for local dev to make a DB snapshot and compare data from snapshot and DB

- lib/compose/index.cjs
- lib/compose/strategies/bal/lieux-dits.cjs
- lib/compose/strategies/bal/numero.cjs
- lib/compose/strategies/bal/voies.cjs
- lib/formatters/csv-bal.cjs
- lib/util/digest-ids-from-bal-uids.cjs
I. Context : 
Currently, we are not importing data from the BAL field "uid_Adresse". We would like to be able to import BAN-IDs from the BAL using this specification : https://github.com/BaseAdresseNationale/ban-plateforme/issues/184
This PR aims to add the BAN-IDs in the data base as following : 
"numero" collection : 
- banId : ID after "`@a:`" suffix
- banIdMainCommonToponym : ID after "`@v:`" suffix
- banIdSecondaryCommonToponyms: not supported for now
- banIdDistrict : ID after "`@c:`" suffix
"voie" collection : 
- banId : ID after "`@v:`" suffix
- banIdDistrict : ID after "`@c:`" suffix
"commune" collection : 
- banId : ID after "`@c:`" suffix
> Added banID field to 'voie', 'numero' and 'commune' schemas + csv-bal export

- lib/api/address/__mocks__/address-data-mock.js
- lib/api/address/utils.js
- lib/api/address/utils.spec.js
- lib/api/common-toponym/__mocks__/common-toponym-data-mock.js
- lib/api/common-toponym/utils.js
- lib/api/common-toponym/utils.spec.js
- lib/api/helper.js
I. Context 
When creating and/or updating common toponyms and/or addresses, we need to be able to check if the linked common toponym IDs and the linked district IDs are already existing in the db.
II. Enhancements 
This PR aims to add two check functions to be sure that the linked commonToponyms (main and secondaries) and the linked district are pre-existing in the DB
> Added checks on common toponym and district existences in db

- .env.sample
- lib/api/address/routes.js
- lib/api/common-toponym/routes.js
- lib/api/district/routes.js
Fix on BAN api url that has been modified from `https://plateforme.adresse.data.gouv.fr` to `https://plateforme.adresse.data.gouv.fr/api`
> Modified ban api url in .env.sample file

- lib/api/district/schema.js
This PR aims to add a `config` key in the district schema to add configuration per district (defaultLanguages, useBanId, ... etc).
Here is the district schema : 
```
banDistrictSchema = object({
id: banID.required(),
labels: array().of(labelSchema).required(),
updateDate: string().trim().required(),
config: configSchema,
meta: metaSchema
})
```
And the config schema (for now) : 
```
configSchema = object({
useBanId: bool()
})
```
> Added config in the district schema

- lib/compose/index.cjs
I. Context 
When doing a "compose" for a non-BAL district, the balData and uid_adresse do not exist. 
II. Fix 
Condition the extraction of the district ID ONLY is data from BAL
> Fix compose when extract district id

- lib/api/address/routes.js
- lib/api/ban-id/routes.js
- lib/api/common-toponym/routes.js
- lib/api/district/routes.js
- lib/api/job-status/routes.js
- lib/api/legacy-routes.cjs
- server.js
I. Context
When using ban-plateforme APIs, we are sending data to create addresses, toponyms, ... etc. Sometimes, the size of the data is higher than the default payload authorized by express (= 100kb).
This PR aims to increase the size of the express payload limit to 20mb (Toulouse BAL being the heaviest BAL and being around 9mb)
> Increased payload express memory limit

- .env.sample
- docker-compose.yml
- lib/api/address/__mocks__/address-data-mock.js
- lib/api/address/models.js
- lib/api/address/routes.js
- lib/api/ban-id/models.js
- lib/api/common-toponym/__mocks__/common-toponym-data-mock.js
- lib/api/common-toponym/models.js
- lib/api/common-toponym/routes.js
- lib/api/district/__mocks__/district-data-mock.js
- lib/api/district/models.js
- lib/api/district/routes.js
- lib/api/job-status/models.js
- lib/api/job-status/routes.js
- lib/util/sequelize.js
- package.json
- server.js
- yarn.lock
I. Context : Currently, the new BAN-ID data schema (address, commonToponym, district) has been deployed in the current mongoDB database in the three different collections : 
- address_test
- commonToponym_test
- district_test
II. Enhancement : 
We want to migrate this new BAN-ID data schema to a PostgreSQL data base
As a consequence, this pull request migrates the models from mongoDB to PostgreSQL with 4 tables : 'Addresses', 'CommonToponyms', 'Districts' and 'JobStatuses' (for more information about the different models, please refer to the 4 model files).
III. How to test.
1. Complete your .env file with the new variables : 
Example : 
```
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DBNAME=ban
POSTGRES_PORT=5432 (ONLY if your are using the docker-compose to deploy) …
```
> Postgres integration for new data schema

- lib/api/common-toponym/schema.js
- lib/util/sequelize.js
This PR aims to make the "geometry" field not required for common toponyms but if existing, it has to match the geometry schema
> Modify common toponym schema for geometry field

- db-migrations/migrations/20230822124246-add-columns-to-job-statuses.cjs
- lib/util/sequelize.js
I. Enhancement : 
This PR aims to add "jobType" and "datType" data into the postgres DB table "JobStatuses" by : 
- Modifying the JobStatus sequelize schema
- Adding a migration file for the PostgreSQL DB
jobType possible values : 
- "insert"
- "update"
- "delete"
dataType possible values : 
- "address"
- "commonToponym"
- "district"
II. How to test : 
1- First, check the structure of your postgresql table "JobStatuses" => you should see that there are no columns "jobType" and "datType"
2- Then, start the migration command : 
`yarn migrate:up --name 20230822124246-add-columns-to-job-statuses.cjs`
3- Finally, check again the structure of your postgresql table "JobStatuses" => now, the two columns "jobType" and "datType" have been added.
4- You can also undo the migration by using the …
> Modify job status db schema with migration file

- .env.sample
- lib/api/address/models.js
- lib/api/common-toponym/models.js
- lib/api/consumers/api-consumer.js
- lib/api/consumers/export-to-exploitation-db-consumer.js
- lib/api/helper.js
- lib/util/sequelize.js
- worker.js
I. Context
We are currently using mongoDB as our unique DB to store data and to exploit them. We have implemented a PostgreSQL relational DB that stores the data from our new BAN-ID schema API. We now need to implement an export mechanism from PostgreSQL (internal DB) to MongoDB (exploitation DB).
1- We have decided to trigger the export of an entire district when : updating, creating and deleting an address or a common toponym from this district.
2- Each time that happens, a job is created (`jobID = districtID`) in a new queue : `export-to-exploitation-db`
3- The job is delayed for `10s`. If a job with the same ID is created during this delay, it replaces the job waiting in the queue.
4- After the `10s`, the job is consumed by a mechanism coded in the …
> First mechanism of export from internal DB (postgres) to exploitation DB (mongo)

- db-migrations/migrations/20230912161927-add-labels-to-addresses.cjs
- lib/api/address/schema.js
- lib/util/sequelize.js
I. Context : 
The field "lieudit_complement_nom" is currently not handled is the new BAN-ID data schema. We need to add it to the data schema and migrate the postgresql structure to add the column
This PR aims to add a new filed in the "address" schema : 
`labels: array().of(labelSchema).default(null).nullable()` <= The field is not required BUT if existing, it has to fit with the already existing `labelSchema` defined as followed : 
```
export const labelSchema = object({
isoCode: string().trim().length(3).required(),
value: string().trim().required(),
})
```
III. How to test
1- Use the migration file to modify your postgreSQL structure (adding a `labels` column into your Addresses table). Here is the following command to start : 
`npx sequelize-cli db:migrate --name …
> Added labels field to address schema and its migration file

- lib/compose/processors/recompute-codes-voies.cjs
deuxième PR liée à l'issue #151 (l'autre PR est sur fantoir).
Permet ici de ne plus renvoyer de code fantoir annulé.
Dans ce cas on préfère renvoyer un pseudo code.
> ajout d'un test si le fantoir trouvé est annulé sans successeur

- docker-compose.yml
- docker-resources/postgres/Dockerfile.dev
- docker-resources/postgres/init-postgis.sh
I. Context : 
In order to be able to calculate some enhanced data (such as common toponym centroids), we would like to use postgis plugin to the postgres DB. 
This PR aims to add the postgis plugin into the postgres docker image by adding : 
- a Dockerfile.dev for the postgres image to install the plugin into the image
- an init-postgis.sh to activate the plugin at the first initialization of the container
> Added postgis plugin into postgres docker image for local development 

- lib/api/consumers/export-to-exploitation-db-consumer.js
Prerequisite : postgis must be installed on postgres DB
I. Context
In the new internal main postgres DB (where we store the data from BAL with BAN-ID), we do not store data that does not come from the BAL. As a consequence, we don't have the additional data we need : fantoir code, postal code, map tiles, ...
This PR aims to calculate, during the export from postgres to mongo, the following data : 
- Fantoir code on common toponyms ONLY
- Postal code on common toponyms and on addresses
- Map tiles on on common toponyms and on addresses
III. How to test
1- Download a BAL (csv)
2- Use the 'initBALIntoBAN' script of ID-Fix to push data into the BAN DB
3- Wait a few seconds for the export to be done 
4- Check in your mongoDB to check on common toponyms and addresses "meta" …
> Added data calculs during exports from postgres to mongo

- lib/api/address/schema.js
- lib/api/common-toponym/schema.js
- lib/api/district/schema.js
- lib/api/schema.js
I. Context
In order to complete our new data schema with the BAL data, we need to store some extra information.
II. Enhancements
This PR aims to add in the new address, common toponym and district schemas the "bal" meta schema (optional field) that will store the following data : 
- idRevision <= data from "API de dépôt"
- dateRevision <= data from "API de dépôt"
- codeAncienneCommune <= field `commune_deleguee_insee` in BAL format,
- nomAncienneCommune  <= field `commune_deleguee_nom` in BAL format,
- isLieuDit <= if number === 99999
III. How to test
1- Post an an address, a common toponym or a district with the following meta : 
"meta": {
"bal":{
"idRevision":"ID_TEST",
"dateRevision":"DATE_TEST",
"codeAncienneCommune": "CODE_ANCIENNE_COMMUNE_TEST",
"nomAncienneCommune": …
> Added bal schema to address, common toponym and district meta schemas

- .env.sample
- lib/api/address/__mocks__/address-data-mock.js
- lib/api/address/routes.js
- lib/api/address/schema.js
- lib/api/address/utils.js
- lib/api/address/utils.spec.js
- lib/api/common-toponym/__mocks__/common-toponym-data-mock.js
- lib/api/common-toponym/routes.js
- lib/api/common-toponym/schema.js
- lib/api/common-toponym/utils.js
- lib/api/common-toponym/utils.spec.js
- lib/api/consumers/api-consumer.js
- lib/api/district/__mocks__/district-data-mock.js
- lib/api/district/routes.js
- lib/api/district/schema.js
- lib/api/district/utils.js
- lib/api/district/utils.spec.js
- lib/api/helper.js
I. Context
We need to be able to partially update an address, a common toponym or a district.
This PR aims to add 3 routes to partially updates the different entities : 
- PATCH /api/address/ (ONLY `id` is required)
- PATCH /api/common-toponym (ONLY `id` is required)
- PATCH /api/district (ONLY `id` is required)
III. How to test
1- On an existing address, use the PATCH /api/address to ONLY update some fields. Example : 
```
PATCH /api/address
[{
id: 000018a1-25ff-46e1-81db-5c0b9e59345e,
number: 4
}]
```
> dissociate put and patch routes for new api

- lib/formatters/csv-legacy.cjs
Cette PR permet d'ajouter des colonnes permettant l'export des banId dans les fichiers d'adressage historiques (adresses et lieux dits).
Pour tester vérifier en faisant un yarn dist (avec les données du département 60)
Ainsi lorsque les banId sont remplis on obtient : 
**fichier des adresses CSV BAL**
`uid_adresse`	cle_interop	commune_insee	commune_nom	...
`@a:83bb0c2e-2afb-4b73-b896-97d6328659ac @v:3587479b-8f4c-4f24-8c60-4d3fcbdf66f5 @c:1db0952a-3e58-47c3-931b-c2eb65d4d1bd`	60447_dwgt8o_00001	60447	Néry ...
**fichier des adresses legacy**
id	`id_ban_adresse	id_ban_toponyme	id_ban_district`	id_fantoir	numero	rep	nom_voie	code_postal	code_insee	nom_commune
60447_fp4p3f_00001	`83bb0c2e-2afb-4b73-b896-97d6328659ac	3587479b-8f4c-4f24-8c60-4d3fcbdf66f5	1db0952a-3e58-47c3-931b-c2eb65d4d1bd`		1 …
> ajout du banId aux fichiers legacy adresses et lieux-dits

- lib/api/address/__mocks__/address-data-mock.js
- lib/api/address/schema.js
- lib/api/address/utils.spec.js
- lib/api/common-toponym/__mocks__/common-toponym-data-mock.js
- lib/api/common-toponym/schema.js
- lib/api/common-toponym/utils.spec.js
- lib/api/district/__mocks__/district-data-mock.js
- lib/api/district/schema.js
- lib/api/district/utils.spec.js
- lib/api/helper.js
- lib/api/schema.js
We are using "yup" package to validate ban-ID data schema.
This PR aims to add : 
- strictMode on validation => validation more strict. For example, dates have to be Date() and not strings
- noUnknown() => cannot have unknown properties in the schemas
> Strict mode and no unknown on validation

- lib/api/address/models.js
- lib/api/address/schema.js
- lib/api/address/utils.js
- lib/api/common-toponym/models.js
- lib/api/common-toponym/schema.js
- lib/api/common-toponym/utils.js
- lib/api/consumers/api-consumer.js
- lib/api/district/models.js
- lib/api/district/schema.js
- lib/api/district/utils.js
- lib/api/helper.js
- lib/api/schema.js
The "meta" field is currently a JSONB type in the postgreSQL DB. When patching this field, the whole object is updated and we loose the data that was already present.
This PR aims to add a separate process of the meta field from the rest of the entity (address, common toponym or district) during a 'patch'. The meta field is know processed by adding the fields to the one already present in the DB. 
Example : 
we have a district in the DB with the following data : 
```
{
"id": "7d40ffcc-57e2-4621-a538-e3ef20b74b8e",
"labels": [
{
"value": "Toulouse",
"isoCode": "fra"
}
],
"updateDate": "2023-01-01T00:00:00.000Z",
"config": null
"meta": {
"insee": {
"cog": "31555"
}
}
}
```
We patch the district with the following body : 
```
{
"id": "7d40ffcc-57e2-4621-a538-e3ef20b74b8e",
"meta": {
"bal": { …
```
> Modified patch update to separetely process the meta field

- scripts/merge-france.sh
fix #306 
script permettant de tester en local le merge des données départementales legacy créées dans le dossier dist.
Ajout de la concaténation des LD sur la France.
Pour tester en local.
Faire un dist permet de générer les fichiers départementaux.
Puis lancer le script en mettant un chemin absolu devant les données et en remplaçant le département 01 par un département existant dans votre dist.
-> /d/ban-plateforme/dist/csv/ et remplacer 01 par un dép existant dans dist
Ce script est à adapter et déployer une fois la PR acceptée sur le serveur de production (cf script build-dist.sh)
> ajout de la concaténation des LD France sur les données legacy

- lib/util/geo.cjs
Lors de la composition des bal un calcul de la tuile (xyz) correspondant aux positions ponctuelles des adresses et voie en vue d'un rendu et service tuilé.
Actuellement le service mvt renvoie bien l'ensemble des adresses présente dans la tuile , mais du fait de l'encodage certaines adresses en bordure sont considérées hors étendu et ne sont pas rendu par des clients (mapbox/maplibre).
il a environ 6k adresses dite fantômes (pour le niveau 14  dernier niveau servi par le serveur)
https://github.com/BaseAdresseNationale/ban-plateforme/issues/324
Cette PR propose d'inclure la tuile de rendu dans la liste des tuiles pour position si le point est en bordure.
- affichage des positions où actuellement il y a default, 
- les 2 tuiles renverront la donnée du point en bordure. (un identifiant est …
> renvoyer la tuile de rendu si le point est en bordure, pas seulement celle théorique

- lib/distribute/cli.cjs
- lib/distribute/writers/csv-with-ids.cjs
- lib/formatters/csv-legacy.cjs
fix #325 
Pour tester lance rla commande en local yarn dist.
-> va créer un nouveau dossier **csv-with-ids** avec les csv legacy avec les 3 colonnes d'ids pour les adresses et 2 colonnes d'ids pour les lieux dits.
-> va remettre dans la structure précédentes (sans banId) les adresses et lieux dit du dossier **csv**.
Penser à communiquer sur ces fichiers 
Penser lors de la mise en production de créer les fichiers France du dossier csv-with-ids
> csv legacy without ids and new csv legacy with ids

- lib/api/address/schema.js
- lib/api/common-toponym/schema.js
- lib/api/consumers/api-consumer.js
- lib/api/consumers/export-to-exploitation-db-consumer.js
- lib/api/consumers/format-to-legacy-helpers.js
- lib/api/district/schema.js
- lib/api/helper.js
- lib/api/position-type-dictionary.json
- lib/api/schema.js
WARNING : need to install postgis in production before deploying this PR.
When BAL data is processed through ID-Fix and new BAN-ID APIs, data is stored in a postgreSQL DB.
For now, the data used by our users is stored in the legacy Mongo DB. In order to be able to use the data that has been processed by new APIs, we need to : 
- export the data from postgreSQL DB
- format the data from our new data schema to the legacy data schema
- import the data into MongoDB
This PR aims to : 
- format the data from our new data schema ([documentation](https://github.com/BaseAdresseNationale/ban-plateforme/wiki/DRAFT%23-Schema-de-la-base-de-donn%C3%A9es-BAN)) to the legacy data format 
- import the data into mongoDB temporary collections* : **communes_legacy**, **voies_legacy**, **numeros_legacy**
*For …
> Added legacy formatting during export from main to exploitation db

- lib/formatters/csv-legacy.cjs
fix #335 
Les colonnes d'identifiants passent en fin de fichier, le nom de la colonne contenant le BanId de la commune passe à idn_ban_commune conformément au nom du format BAL AITF 1.4.
A faire ensuite en production rajouter la partie de script permettant de produire les fichiers France entière
> modification du fichier csv historique avec ids

- lib/util/geo.cjs
Example of the logs to clean :
> Cleaned log

- .env.sample
- lib/util/sequelize.js
In order to make a progressive infrastructure evolution of the postgresDB, We need to be able to set the postgresql db access port easily.
This PR adds the possibility to set the postgresql port through an env variable : 
- POSTGRES_PORT = ... (the desired port)
- add a POSTGRES_PORT env variable to the .env file in production (it will work without it because we have set a default value in the code if the variable is empty).
> Added postgres port env variable

- worker.js
To fix concurrency issues on new API (consumers can consume jobs in an order different than the order of the api calls), we are going to set pm2 to start only one worker.js process (modifying ecosystem.json)
In order to improve concurrency on the legacy "compose" this PR aims to switch concurrency number from 2 to 4 (everything will run on one node process).
> Added 4 concurrency processes to legacy compose

- lib/api/address/__mocks__/address-data-mock.js
- lib/api/address/__mocks__/address-models.js
- lib/api/address/models.js
- lib/api/address/routes.js
- lib/api/address/schema.js
- lib/api/address/utils.js
- lib/api/address/utils.spec.js
- lib/api/common-toponym/__mocks__/common-toponym-data-mock.js
- lib/api/common-toponym/__mocks__/common-toponym-models.js
- lib/api/common-toponym/models.js
- lib/api/common-toponym/routes.js
- lib/api/common-toponym/schema.js
- lib/api/common-toponym/utils.js
- lib/api/common-toponym/utils.spec.js
- lib/api/schema.js
When sending data from id-fix, we need to be able to ONLY update the addresses or toponyms that are different from the database.
This PR aims to add the following behavior for the delta-report routes : 
- retrieve the hash (md5) from the id-fix meta
- compare the hash to the one sent <= if hashes are different, the delta-report route must add the address/toponym IDs to the "update" key or the object returned. If not, delta-report routes must not return them.
1- Clone the branch
2- Also clone the branch of this PR : https://github.com/BaseAdresseNationale/id-fix/pull/70
3- Use the initBALIntoBAN from id-fix to push a BAL => md5 hashes are going to be stored in the database the first time
4- Use the same script a second time => nothing should be updated as md5 are the same.
Info : to check …
> Delta report and id-fix hash

- lib/api/legacy-routes.cjs
- lib/formatters/csv-bal.cjs
Currently, using ban-plateforme API, we can download a district BAL from BAN DB as csv file ONLY in version 1.3. The adresse.data.gouv website is using the api on the "commune" page : 
To be able to dowload new 1.4 BAL version, we need to adapt the current behavior, starting by the API : 
`/ban/communes/:codeCommune/download/:downloadFormat/:downloadType`
This PR aims to enhanced the current download API by : 
- adding a new query parameter : "version" (that only accepts '1.3' and '1.4' values)
If the query parameter is not set (as it is currently on the website), the version 1.3 is set by default
- Pre-requisite : Have at least one district data in the BAN mongo DB
- Using Postman (or similar), call the following routes : 
GET http://localhost:${your_port}/ban/communes/${your_commune}/dow …
> Added version query param to download csv api route

- db-migrations/migrations/20240404132816-clear-historic-mechanism.cjs
- db-migrations/migrations/20240404134334-add-range-validity-and-is-active.cjs
- db-migrations/migrations/20240404140053-clear-delete-right.cjs
- db-migrations/migrations/20240404142921-rebuild-historic-tables.cjs
- db-migrations/migrations/20240404142956-rebuild-historic-trigger.cjs
- lib/api/address/__mocks__/address-data-mock.js
- lib/api/address/__mocks__/address-models.js
- lib/api/address/models.js
- lib/api/address/utils.js
- lib/api/address/utils.spec.js
- lib/api/common-toponym/__mocks__/common-toponym-data-mock.js
- lib/api/common-toponym/__mocks__/common-toponym-models.js
- lib/api/common-toponym/models.js
- lib/api/common-toponym/utils.js
- lib/api/common-toponym/utils.spec.js
- lib/api/consumers/export-to-exploitation-db-consumer.js
- lib/api/district/models.js
- lib/api/district/utils.js
- lib/util/sequelize.js
We need to be able to deactivate and re-activate an address, a common toponym or a district. We also need to have in the historic a trace of a deactivation and reactivation. 
This PRs aims to :
- Add a "isActive" column in all tables (address, common_toponym and district)
- Modify all the "destroy" fonctions to "update" with the flag : isActive = false
- Modify all the "updates" functions to "update" with the flag : isActive = true (to be able to re-activate an item with a simple update (so that a district can simply re-activate an item simply by adding again the line in the bal)
- Rebuild the historic mechanism
I. Initialization : 
If using docker and docker-compose : 
- Start the following command : 
`docker compose up --build -d` <= migrations are done automatically when starting the …
> [PRIO] Active state and historic mechanism

- lib/models/ban.cjs
With the deployment of the new technical platform, we need to have data on the number o district that uses banIDs
This PR : 
- adds a "nbCommunesAvecBanId" calcul is the stat compute
> Add with ban id stats

- lib/models/ban.cjs
Fix : the "key" to use for the "nbCommunesAvecBanId" is `withBanId` and not `useBanId`
> Fixed nbCommunesAvecBanId stats

- lib/api/address/__mocks__/address-models.js
- lib/api/address/models.js
- lib/api/address/utils.js
- lib/api/address/utils.spec.js
- lib/api/common-toponym/__mocks__/common-toponym-models.js
- lib/api/common-toponym/models.js
- lib/api/common-toponym/utils.js
- lib/api/common-toponym/utils.spec.js
When creating the delta report to inform id-fix what to create/update/delete, we were only considering the context of a district for "updates"
This PR modified the delta-report behavior so that :
- If an address or a common toponym is outside the district, it is now considered in the "update" array (instead of the "unauthorized" array).
> Modified delta report to update items outside district

- db-migrations/seeders/20240417084446-init-districts.cjs
- package.json
- toolbox.dev/scripts/compare-data-from-db-snapshot-and-current-db.js
- toolbox.dev/scripts/db-snapshot.js
When working locally, we need to have data into the db to develop, to test, ... etc
This PRs aims to add a "seed" mechanism to be able to insert/modify/delete data into the DB easily thanks to sequelize-cli.
1- Run the command : 
`npm run seed:up`
2- Check you local db : the data from the file `db-migrations/seeders/20240417084446-init-districts.cjs` must have been inserted into your local db.
> [Init DB with data] - Add seed mechanism

- lib/api/consumers/export-to-exploitation-db-consumer.js
- lib/api/consumers/format-to-legacy-helpers.js
When using the new technical architecture (new APIs and new postgres DB), we export the data from postgres to mongo when we detect a change. If the script that export data from postgres to mongo, we are calculating the 'legacy' id for the addresses and the common toponyms. In the 'legacy' compose, there were simplifications to have a unique identifier for those legacy ids. In the new technical architecture, as we based the unicity of addresses and common toponyms on their new ban IDs, the 'legacy' can sometimes not be unique (as calculated with fantoir code or pseudo code that can be the same for different entities).
This PR aims to make sure the legacy id for the common toponyms is unique. Here is the mechanism : 
- If a fantoir code is found on a common toponym, we create a legacy id …
> Fixed legacy idVoie duplicates when exporting data from postgres to mongo

- lib/distribute/cli.cjs
- lib/distribute/writers/csv-bal-with-lang.cjs
- lib/formatters/csv-bal.cjs
- package.json
- Ajout des langues régionale dans les exports départemental
> feat: export csv bal with lang

- lib/compose/cli.cjs
To compose a district manually, ban-plateforme has a "compose" command that can get a insee code or a list of insee codes as arguments. The issue is that when passing a code insee that has a '0' at the beginning, the `minimist` lib converts it to number. Example : `yarn compose 08053` => the code insee is converted to `8053` by the lib
This PR adds an option to the 'minimist' lib to only get string arguments.
From `minimist` documentation : 
`Numeric-looking arguments will be returned as numbers unless opts.string or opts.boolean contains that argument name. To disable numeric conversion for non-option arguments, add '_' to opts.string.`
> Fixed legacy compose cli to get only string args

- lib/compose/import-from-api-depot.cjs
- package.json
- yarn.lock
Le profile du validateur utilisé par ban-plateform `relax` n'existe pas.
Il n'était pas pris en compte dans la version 2.17.0 du validateur si il n'était pas bon.
Utilisation du profile `1.3-relax` qui est celui utilisé dans toutes les autres briques
> fix: bug validateur profile

- lib/compose/sources/cadastre.cjs
- lib/compose/sources/ftth.cjs
Exemple : les données d'assemblage de la commune voisine vienne "polluer" l’affichage de la BAL de Niedermorschwihr https://adresse.data.gouv.fr/base-adresse-nationale/68237_0100#15.61/48.101253/7.236892
Modification du buffer à 50m pour ftth et cadastre
Fix:#423
> Changement Buffer Cadastre et ffth

- db-migrations/migrations/20240618155810-init-common-toponym-view.cjs
- db-migrations/migrations/20240618155829-init-address-view.cjs
- lib/api/consumers/export-to-exploitation-db-consumer.js
- créer vue adresses (avec toutes les données calculée par la query d'export de postgres => mongo)
- créer vue common_toponym (avec toutes les données calculée par la query d'export de postgres => mongo)
- Remplacer les queries par les vues.
issue #434
> Initialiser les vues d adresses et de toponymes communs

- lib/api/consumers/format-to-legacy-helpers.js
Context : there was an error in the code that generates an id with the sha 256 hash method. The code was slicing the hash from index 0 to 5 (taking the first 5 characters) instead of slicing it from index 0 to 6 (taking the first 6 characters). We need a 6 character id.
> Fix generated legacyCommonToponymId with sliced sha256 hash

- lib/compose/index.cjs
Fix : getting the district ID already generated from our main DB instead of generating it again.
> Fixed district ID on assemblage by fetching our main db

- lib/compose/ask-compose-all.cjs
- lib/compose/cli.cjs
- lib/compose/index.cjs
- lib/compose/worker.cjs
- package.json
This PR adds : 
- a check in the legacy composition to ignore composition on a assemblage that already has a banId
- an option to the "compose" command to be able to force composition
- an option to the "askComposeAll" command to be able ask a composition on all district with a force option
> Prepare compose all generate id on assemblage

- lib/api/schema.js
In legacy compose algorithm, the `cle_interop` (and `deprecatedID` that is a sub-part of the `cle_interop`) BAL data is not taken from the BAL file but re-calculated in ban-palteforme.
In our new data architecture, we want to add the possibility for a district to retrieve the value given in the BAL file ONLY if valid.
This PR aims to add : 
- the `cleInterop` and `deprecatedID` keys in the bal schema.
> Added cleInterop in bal meta schema

- docker-compose.yml
- lib/api/consumers/export-to-exploitation-db-consumer.js
- lib/api/consumers/format-to-legacy-helpers.js
Currently, when transfering data from main db (postgresql) to our exploitation db (mongodb), we are, in this order, : 
- deleting old data from mongo
- creating temp sql tables with code postal calculation
- then, page per page (page = 100 items) we are : 
- getting data
- formating data
- inserting data into mongo
This can take a long time to processing especially for big cities like 'Toulouse' for example (around 15 minutes). As a consequence, the data in our exploitation db, that has been deleted at the beginning, is unavailable during that processing time.
To solve this issue, this PRs adds a mechanism of "temp collection" : 
- all the processed data will be inserted in those temp collection (temp_voies_${cog} and temp_numero_${cog})
- when all the data is inserted, the old data is …
> [From Postgres to Mongo] : Added temp collections to lower data unavailability time

- lib/api/address/routes.js
- lib/api/common-toponym/routes.js
- lib/api/district/routes.js
- lib/api/export-to-exploitation-db/routes.js
- lib/api/routes.js
In order to force an update from postgres to mongo, we need a new API route
This PR adds a new route : 
- POST `export-to-exploitation-db/districts` that takes a body with the list of district IDs in an array : `{districtIDs:["","",...]}`. This route adds a job in the "export-to-exploitation-db" queue for each district ID requested.
> New api route to force export from postgres to mongo

- lib/api/consumers/export-to-exploitation-db-consumer.js
- lib/api/consumers/format-to-legacy-helpers.js
In our new system architecture, the data of the` ancienne commune` is retrieved from the BAL data (columns `commune_deleguee_insee` and `commune_deleguee_nom`). If the district does not enter this data, we are not currently calculating it (as it was the case in our legacy system). 
In order to fix this issue, this PR adds the old data calculation for the `ancienne commune` from the `gazetteer` db.
> Added calcul of old district from gazetteer db when transferring data from postgres to mongo

- lib/api/address/schema.js
- lib/api/consumers/export-to-exploitation-db-consumer.js
- lib/api/consumers/format-to-legacy-helpers.js
- lib/compose/processors/update-communes.cjs
- lib/util/gazetteer.cjs
In our new system architecture, the data of the` ancienne commune` is retrieved from the BAL data (columns `commune_deleguee_insee` and `commune_deleguee_nom`). If the district does not enter this data, we are not currently calculating it (as it was the case in our legacy system). 
In order to fix this issue, this PR adds the old data calculation for the `ancienne commune` from the `gazetteer` db.
> Calculate commune ancienne export postgres mongo - gazetteer implementation

- lib/api/address/routes.js
- lib/api/ban-id/routes.js
- lib/api/certificate/routes.js
- lib/api/common-toponym/routes.js
- lib/api/district/routes.js
- lib/api/export-to-exploitation-db/routes.js
- lib/api/helper.js
- lib/api/job-status/routes.js
- lib/api/postal-datanova/routes.js
In order to have homogeneous api responses, this PR adds a : 
- handleAPIResponse function that handle the different response status and structure
> Improved api response format and homogeneity

- db-migrations/migrations/20241122171119-delete-views.cjs
- db-migrations/migrations/20241125124117-grant-rights-on-external-schema.cjs
- lib/api/consumers/export-to-exploitation-db-consumer.js
- lib/api/consumers/format-to-legacy-helpers.js
- lib/api/consumers/sql-queries.js
The transfer process from postgresql to mongodb is using stored views in postgresql to calculate some extra data such as postal code data and geo data (bounding boxes, centroid, ...). Currently, this process can be quite long.
In order to improve the performances of the transfer process, this PR : 
- delete the stored view (some calculs were done on all the addresses and common toponyms of the database instead of targeting only a specific district),
- add dynamic views to target only one district,
- add rights for ban-plateforme user to use the "external" schema tables.
- modify the structure of the views to improve performances (delete subqueries in CASE statements that lower the perf + add Common Table Expressions (CTEs) to improve readability).
> Added dynamic views (instead of the stored views)

- lib/api/consumers/format-to-legacy-helpers.js
- lib/models/commune.cjs
In order to correctly activate the certificate for the district that have activated it, we need to have more information in our exploitation db (mongo), coming from our main db (postgresql).
this PR adds :
- district `config` on all items transferred from our main db (postgresql) to our exploitation DB (mongodb) : address, common toponym and district in our 
- flag `withBanId` on all items transferred from our main db (postgresql) to our exploitation DB (mongodb) : address, common toponym (it was already exported on district items).
This PR also adds the config district in the field returned by the `lookup`
> Added district config in export to exploitation db

- db-migrations/migrations/20241206163355-add-right-on-postal-area-id-sequence.cjs
- lib/api/postal-area/models.js
- lib/api/postal-area/routes.js
- lib/api/routes.js
- lib/util/sequelize.js
The postal areas data is changing and needs to be updated in our database
This PR adds : 
- a new API route PUT /postal-area/district/cog/${cog}
body structure : 
```
[
{
"postalCode": "postal code 1",
"geometry": {
"type": "MultiPolygon",
"coordinates": [...]
}
},
{
"postalCode": "postal code 2",
"geometry": {
"type": "MultiPolygon",
"coordinates": [...]
}
},
]
```
This route will replace the postal areas for an entire district.
> Added postal area update route api

- lib/api/address/utils.js
- lib/api/common-toponym/utils.js
Fix : addresses and common toponyms needs to be updated when their district ID is different and they are part of the same department.
> Added case in delta report when department are identical

- lib/api/district/schema.js
Ajout d'une clé `defaultBalLang` dans le champ `config` de la table `district` (Postgres).
Permet de pouvoir accepter les langages autres que `fra` dans le champ `voie_nom`
> ajout default langage bal
