BaseAdresseNationale/ban-plateforme

lib/compose/sources/cadastre.js
lib/compose/sources/ign-api-gestion.js

Modification du buffer sur le cadastre à 200 mètres comme ca été fait sur adresses-ftth
Fix #58

adresses implantées sur la mauvaise commune

---

.dockerignore

Add dockerignore reference in .dockerignore so that the .dockerignore file is not copied inside the image

Added file in .dockerignore

---

package.json

This pull request aims to modify : 
- Package name from @etalab to @ban-team
- Package version from 0.0.0 to 1.0.0

Modified name attribute to @ban-team/ban-plateforme in package.json

---

package.json
yarn.lock

Mise a jour de validateur-bal v2.12 après la mise a jour shared-data 1.2

Update validateur-bal v2.12

---

lib/compose/processors/recompute-codes-voies.js

fix ref to fantoir

---

lib/api/address/__mocks__/address-models.js
lib/api/address/models.js
lib/api/address/routes.js
lib/api/address/utils.js

Context : 
When a BAL is going to be published with BAN-IDs, we need to be able to get the information of which addresses have to be created, which have to be updated and which have to be deleted. 
Enhancements : 
We have created a new api route that returns a delta report. Here are the information about this route : 
- endpoint : /address/delta-report
- body : `{addressIDs:[...], codeCommune:'...'}` (addressIDs array and codeCommune string are mandatory)
- response : `{idsToCreate:[...], idsToUpdate:[...], idsToDelete:[...]}`
How to test : 
In your local environnement, insert two news addresses with the POST /address route. Here is an example of the body : 
```
[
{
"id": "00000000-0000-4fff-9fff-00000000000a",
"codeCommune": "12345",
"idVoie": "00000000-0000-4fff-9fff-00000000001a", …
```

Added address ID delta report api route

---

lib/api/common-toponym/models.js
lib/api/consumers/api-consumer.js
server.js

Fixing missing file error when starting ban-plateforme API

Fix common toponym routes

---

lib/compose/bal-garbage-collector/index.js
lib/compose/bal-garbage-collector/models.js

Default export issue resolved for the garbage collector function

Fixed garbage collector exports

---

lib/api/address/routes.js
lib/api/address/utils.js
lib/api/common-toponym/models.js
lib/api/common-toponym/routes.js
lib/api/common-toponym/schema.js
lib/api/common-toponym/utils.js
lib/api/consumers/api-consumer.js
lib/api/helper.js

This PR contains : 
- Code refactoring (helper.js file added to factorized the check function between address and common toponym)
- Add Multi-delete route for common toponym

Added common toponym multi-delete api route

---

lib/api/address/utils.js
lib/api/common-toponym/utils.js

Code optimization that uses :
- Set to improve membership checks
- Removing one unnecessary iterations on addressIDs and commonToponymIDs

Modified delta report util function to optimize code

---

lib/api/common-toponym/__mocks__/common-toponym-data-mock.js
lib/api/common-toponym/schema.js
lib/api/common-toponym/utils.spec.js
lib/api/district/__mocks__/district-data-mock.js
lib/api/district/schema.js
lib/api/district/utils.spec.js

Fix: ISO Lang v3 has Length of 3

---

lib/api/ban-id/helpers.js
lib/api/ban-id/models.js
lib/api/ban-id/routes.js
server.js

#145 
Cette PR ajoute une route de GET renvoyant un tableau d'uuidv4
forme de l'url : /ban-id?quantity={nbId}
Attend en paramètre le nombre d'id souhaité, par défaut 1, maximum 100 000

Route de fourniture de BanID

---

lib/api/legacy-routes.cjs
lib/models/ban.cjs

PR sur adresse.data.gouv : https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1509
Mise à jour du backend pour permettre le filtrage du déploiement BAL par EPCI et département.

Filtrage des statistiques de déploiement BAL par code commune

---

lib/api/legacy-routes.cjs
lib/models/ban.cjs

Add a POST route and a service to get stats filtered by communes

feat: add a route to get filtered stats

---

lib/compose/import-from-api-depot.cjs
package.json
yarn.lock

https://github.com/BaseAdresseNationale/validateur-bal/issues/76
https://github.com/BaseAdresseNationale/api-depot/issues/89
https://github.com/BaseAdresseNationale/validateur-bal/pull/75

update validator 2.15.0

---

lib/api/common-toponym/__mocks__/common-toponym-data-mock.js
lib/api/common-toponym/schema.js
lib/api/district/__mocks__/district-data-mock.js
lib/api/district/schema.js

This PR aims to : 
- switch 'label' field to 'labels' (as it is an array of label)

Modify ban id data schema : label => labels

---

lib/api/legacy-routes.cjs

update id-fix main route url from `${API_IDFIX_URL}/district/${codeCommune}/` to `${API_IDFIX_URL}/district/cog/${codeCommune}/`

Updated id-fix route url

---

lib/distribute/writers/addok.cjs

pour les communes avec arrondissement

correction pour Marseille, Lyon et Paris

---

lib/util/sequelize.js

In order to improve data fetching from postgresql, this PR adds indexes on important columns

Added indexes

---

lib/api/legacy-routes.cjs

Pre-requisite : merge the following PR : https://github.com/BaseAdresseNationale/id-fix/pull/66
This PR aims to modify the main route url for id-fix : from `/district/cog/:cog` to `compute-from-cog/:cog`

Modified id-fix main route name

---

lib/api/district/routes.js

Fix : adding lastRecordDate to get district by cog api response

Fix get district by cog api response adding lastRecordDate property

---

package.json
scripts/download-datasets.cjs
yarn.lock

- Maj dependance gazetteer et découpage administratif
- Modification url appel gazetteer.sqlite

Maj dependances pour COG

---

lib/formatters/geojson.cjs

issue https://github.com/BaseAdresseNationale/ban-plateforme/issues/403

Source Names Optimization 

---

package.json
yarn.lock

package.json: 
- @ban-team/validateur-bal 2.17.0 => 2.19.0

validator cog 2024

---

package.json
yarn.lock

This reverts commit 5657c0a36824c3c2ac0f431603638792c7705d23.

Revert "validator cog 2024"

---

lib/models/commune.cjs

Ajout dans les champs retournés par le lookup/ pour les voies et les lieux-dits : 
- source
- position
- parcelles

Added projection fields to lieu-dit lookup

---

lib/api/consumers/export-to-exploitation-db-consumer.js
lib/api/consumers/format-to-legacy-helpers.js

This reverts commit 2e466c73197d23c61db8117e59c16c3924c4a6d5, reversing changes made to ca4db4d09e50e17e5cf6e6c596ca0aac7ee5bccb.

Revert use of gazetteer

---

package.json
yarn.lock

mise à jour codes-postaux 4.0.0 - > 4.1.2
COG 2024

upgrade codes-postaux (4.1.2)

---

lib/api/address/routes.js
lib/api/ban-id/routes.js
lib/api/certificate/routes.js
lib/api/common-toponym/routes.js
lib/api/district/routes.js
lib/api/export-to-exploitation-db/routes.js
lib/api/helper.js
lib/api/job-status/routes.js
lib/api/postal-datanova/routes.js

This reverts commit aec1c6c8c3981080d204281b643d51068fb427a6, reversing changes made to 7670269cefffc00eebf607245f53bc6f988c83c7.

Revert "Merge pull request #495"

---

package.json
yarn.lock

Mettre a jour les packages pour les langues régionals oc-nicard et oc-prevecal

feat: update package for regional lang

---

lib/api/certificate/models.js
lib/api/certificate/utils.js

Ajout du lieu-dit (lieuDitComplementNom) dans le document certificat.

certificat: ajout du lieu-dit

---

db-migrations/migrations/20250624094526-init-session.cjs
db-migrations/migrations/20250624094535-init-action.cjs
docker-compose.yml
lib/api/action/models.js
lib/api/action/schema.js
lib/api/district/models.js
lib/api/district/routes.js
lib/api/routes.js
lib/api/session/models.js
lib/api/session/routes.js
lib/api/session/schema.js
lib/middleware/pro-connect.js
lib/models/commune.cjs
lib/util/sequelize.js

https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/2136

add enable addressing certification.
